### ISSUE TITLE
[SUGGESTION] king of the ladder items

### ISSUE THREAD

**Issue by Truongvv10** [Despical/KOTL#11]
Possible to add items/commands upon joining the KOTL? 

1. Preferably I would want commands to be executed upon joining king of the hill to give players a kit using CMI kiteditor for example. This means you don't have to go thru coding a custom UI to put items in, and save them in a different file. 

2. But if you rather go the rout of having items put in UI and when people enter, they get those items you can. Just make sure it saves all the name and NBT tags for custom items to be used in the game. 

Either options are fine, just make sure that item-drop is disabled so no one can duplicate items

**Comment by Despical** [comment]
Maybe I can add reward to execute when players join an arena and you can execute your command to give a kit or items.
