### ISSUE TITLE
King spam if two players same time on the top

### ISSUE THREAD

**Issue by SirvydasS** [Despical/KOTL#12]
https://youtu.be/AEF1aCSU17w

**Comment by Despical** [comment]
I tried this one on my local server but event is not triggering until the pressure plate released and someone get on it. I don't know how do you trigger the event infinitely so there is no proper fix that at least for now.

**Comment by SirvydasS** [comment]
I think the bug is with iron and gold plates because with wood plates I don't have the issue.

**Comment by Despical** [comment]
Hmm, I'll check it again.
