### ISSUE TITLE
Placeholders aint working on scoreboards

### ISSUE THREAD

**Issue by eesti2rikas** [Despical/KOTL#14]
Yo wsp...i tryed to use %kotl_{arenaid}:king% but it doesnt work and idk how to fix it
![image](https://github.com/Despical/KOTL/assets/146473247/8faad0b6-0d90-478d-8749-ec747b96e826)

**Comment by eesti2rikas** [comment]
dont mind the deaths there i am chaning that

**Comment by Despical** [comment]
[Valid placeholders for scoreboard](https://github.com/Despical/KOTL/wiki/Frequently-Asked-Questions#scoreboard-variables) and, also scoreboard currently does not support PlaceholderAPI.

**Comment by Despical** [comment]
[Valid placeholders for scoreboard](https://github.com/Despical/KOTL/wiki/Frequently-Asked-Questions#scoreboard-variables) and, also the scoreboard supports PlaceholderAPI. `%kotl_kotl1:king%` should work in this case.

**Comment by eesti2rikas** [comment]
ok i didn't know that i should delete the {} bc usualy the would be kept...I recommend u change {} to () but thx :D

**Comment by Despical** [comment]
Yeah, I should change them to not confuse people. Thank you, I'm closing the issue. Feel free to open another one.
