### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by capubara** [Despical/KOTL#15]
i use cmi for giving money for people,when i place commands into rewards it doesn't work, how can i ive $ for people, example command eco give not works too
![image](https://github.com/Despical/KOTL/assets/161635835/9f8a437b-805c-4dd6-b3f3-bf5c88540719)

**Comment by capubara** [comment]
author what is should do,why you closed the issue

**Comment by Despical** [comment]
> author what is should do,why you closed the issue

Just [update the plugin](https://www.spigotmc.org/resources/king-of-the-ladder.80686/). It should work fine now.

**Comment by capubara** [comment]
thanks, it works
