### ISSUE TITLE
Auto replacing "score" statistic 

### ISSUE THREAD

**Issue by capubara** [Despical/KOTL#16]
When in the arena there are more then 1 player, "score" statistic will auto replacing to "score" statistic another person"

https://github.com/Despical/KOTL/assets/161635835/dd83fcaa-3bf0-4962-9c77-8cefe008feab

**Comment by Despical** [comment]
I've just tried and the game is working fine with 1 or more players. What is your server version?

**Comment by capubara** [comment]
1.20.1

**Comment by Despical** [comment]
Is there any possibility that you have created 2 instance of the game at the same locations?

**Comment by capubara** [comment]
![image](https://github.com/Despical/KOTL/assets/161635835/37037d97-0a1c-4e08-b568-6d09657f4be2)

**Comment by Despical** [comment]
I've checked in 1.20.1 and still no problem.

```
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-1996 (MC: 1.20.1)
```

What is your server software and try to delete plugin folder and reload the server then recreate an arena.

**Comment by capubara** [comment]
what you mean about software,i don't understand,is it core?
like spigot?

**Comment by Despical** [comment]
Yes, can you send the output of /version command.

**Comment by capubara** [comment]
>[14:19:51]
[Server thread/INFO
] [/]:
[14:19:51] [Server thread/INFO]
[/]: Версия плагина СМІ: 9.6.1
0.6 SqLite→> 9.7.0.2
[14:19:51] [Server thread/INFO]
[/]: CMILib: 1.4.5.2 →> 1.4.6.
1
[14:19:51] [Server thread/INFO]
[/]: Версия сервера: Spigot 1.
20.1-R0. 1-SNAPSHOT-
[14:19:511 [Server thread/INF01
[/]: СМІ Экономика: Включено В ерсия Vault: 1.7.3-СМІСМІ Чат:
Выключено
[14:19:51] [Server thread/INFO]
[/]: Модули -> 52 включено 7 о
тключено: flightCharge, chatBub
ble, tablist, votifier, portals , headDrop, playerChatTag

**Comment by Despical** [comment]
I still couldn't managed to reproduce the issue. Here is the [video](https://youtu.be/LA-xSgk80EQ) that I've just recorded.

**Comment by Despical** [comment]
Try to use a newer fork suh as Paper or Purpur.

**Comment by Despical** [comment]
@capubara Any updates?

**Comment by capubara** [comment]
of core?

**Comment by capubara** [comment]
no ,score is autoreplacing

**Comment by Despical** [comment]
Did you try with Paper or a newer fork?

**Comment by capubara** [comment]
No,and i will no do it due to the fact i have mods and i need hybrid core, these guys (Ketting)
are as native for me

**Comment by Despical** [comment]
Okay then, you can disable scoreboard and use your own scoreboard plugin if you have. You can also use scoreboard placeholders, here is the list of [placeholders](https://github.com/Despical/KOTL/wiki/PAPI-Placeholders) and [scoreboard placeholders](https://github.com/Despical/KOTL/wiki/Frequently-Asked-Questions#scoreboard-variables).
