### ISSUE TITLE
allow disabling max health on arena enter (and maybe this gamemode change...)

### ISSUE THREAD

**Issue by homerek111** [Despical/KOTL#18]
Hello, would it be possible to allow disabling (in config) the feature that gives player max health after entering arena??? Also it would be useful to allow disabling forcing survival gamemode on arena enter

I would be really greatful if you manage to add this disabling option :)

**Comment by Despical** [comment]
If you mean healing the players when they enter an arena and want to disable it, you can add `health` to the list under `Inventory-Manager.Do-Not-Restore` section in config file.

An option can be added for player's game mode.

**Comment by homerek111** [comment]
> If you mean healing the players when they enter an arena and want to disable it, you can add `health` to the list under `Inventory-Manager.Do-Not-Restore` section in config file.
> 
> An option can be added for player's game mode.

I want it not to change anything at all - to allow enter the arena and dont touch player's health/hunger/gamemode etc.
-> I think there could be an option to disable all actions on player's parameters

Health problem is SOLVED with:
`Inventory-Manager:
  Do-Not-Restore:
    - "health"`
    
BUT

I also tried disabling changing hunger and gamemode
`  Do-Not-Restore:
    - "health"
    - "food"
    - "gamemode"`
and it is still changing hunger and gamemode... (I also tried with `hunger` instead of `food`)



Could you please allow disabling hunger and gmamemode change as well? :)

**Comment by Despical** [comment]
I have added an option to set a custom game mode other than survival when players enter an arena and added new attributes to not restore hunger, saturation, game mode, etc.

**Comment by homerek111** [comment]
> I have added an option to set a custom game mode other than survival when players enter an arena and added new attributes to not restore hunger, saturation, game mode, etc.

great! That sound awesome - i will test everything when you release it on spigot :))
