### ISSUE TITLE
Message file wird nicht gespeicher

### ISSUE THREAD

**Issue by Grafhugo** [Despical/KOTL#2]
Jedes mal wenn ich den Server neustarte wird wird die message config neu generiert bzw alle infos die ich dazu geschrieben habe ignoriert.

**Comment by Despical** [comment]
Thanks for sharing. I'll fix as soon as possible and next time please use English for issues.

**Comment by Grafhugo** [comment]
sure no problemm ^^

**Comment by Despical** [comment]
Closing issue. Fixed in https://github.com/Despical/KOTL/commit/7bb18f9e97964db3904017386aa71c16402a7afa
