### ISSUE TITLE
spam king 

### ISSUE THREAD

**Issue by aliakbartnt** [Despical/KOTL#22]
when e two player on the plate . spam who is king and give e reward with to player and its spam it

pls fix it . or say me how i can fix this 

![screenshot](https://s8.uupload.ir/files/screenshot_(905)_qsm.png)

and this is false : 
 Should we let players become king in a row?
Become-King-In-A-Row: false

**Comment by Despical** [comment]
Which plate are you using? If it is gold or iron then you should change it because they allow spamming.

**Comment by aliakbartnt** [comment]
oh ok i use gold plate  XD
