### ISSUE TITLE
Spam der Druckplatte

### ISSUE THREAD

**Issue by Grafhugo** [Despical/KOTL#3]
Wenn ein spieler auf der Druckplatte springt kriegt er jedes mal punkte + es wird dauerhaft im chat geschrieben das er nun könig ist

**Comment by Despical** [comment]
I'll fix when I have time. Issue will be closed when the fix came out.

**Comment by Despical** [comment]
@Grafhugo Which version is your server?

**Comment by Grafhugo** [comment]
1.17.1

**Comment by Despical** [comment]
1.17.x is not supported yet. I'll fix it soon.

**Comment by Despical** [comment]
Closing issue. Fixed in https://github.com/Despical/KOTL/commit/7bb18f9e97964db3904017386aa71c16402a7afa
