### ISSUE TITLE
Last King : Nobody

### ISSUE THREAD

**Issue by UmaruDoma** [Despical/KOTL#4]
![Screenshot 2022-11-25 221545](https://user-images.githubusercontent.com/17725068/204056003-8bc77cfe-0382-4a35-ad68-d6bd4bb45d51.jpg)
Hi,
I followed the Tutorial
/kotl create Meckmine
/kotl edit Meckmine
Set the arena, Set the plate and the hologram.
What did I miss?
The King:Display and the arena disappeared after registering the arena.
Server Spigot 1.19.2
Sabine

**Comment by Despical** [comment]
Hello there, I have released a new update that fixes a bug about arena registering that update may solve your problem. If it doesn't you can try to delete arena and recreate it again. There can be also errors so please check out the server logs.
