### ISSUE TITLE
Stop a player from becoming king twice in a row

### ISSUE THREAD

**Issue by joshwenke** [Despical/KOTL#7]
If you become king, you can step off and back on the pressure plate to increment your score. Perhaps you could stop a person from doing this individually and require that someone else becomes king before you can re-claim your spot as king? You can step off and hold shift while you go back on to cause this to happen.

**Comment by Despical** [comment]
Yes, I know about this. Maybe I should add new spawn points to the game area so players can be teleported after anyone becomes king and everyone will still have chance to be king.
