### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by haroldrc** [Despical/KOTL#8]
spigot ver: 1.8
pl ver: 2.5.2

![2023-03-10_18 43 39](https://user-images.githubusercontent.com/29206120/224386868-06448dad-43c8-4e77-80c2-b32935e1afc4.png)

the player is not tipped back (Before some updates it didn't give this problem)

**Comment by Despical** [comment]
Probably something is wrong with arena configuration. Try to recreate the arena and setup again. I have also released a new version and added option to not let players become  king in a row. If it is still happening in the updated version please re-open the issue.
