### ISSUE TITLE
Health saving issue

### ISSUE THREAD

**Issue by Truongvv10** [Despical/KOTL#9]
Hi, I'm using Aurelium Skills and having issues with health not saving properly. 

When having `Inventory-Manager-Enabled: true`, everything works seamlessly except for the health when using plugins that modify players heath, for example Aurelium Skills. 

What happens is whenever I enter the arena, my health is fine with the same numbers 20. But when I leave the arena, my health seem to go up. What I'm thinking is that Aurelium Skills modifiers your current health, so when the health rolls back to it's old self, it puts the modifier on top of it, instead of your base health. 

Solution would be rolling back to base health instead of current health? 

**Aurelium Skills Plugin Link:**
https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/

**Comment by Despical** [comment]
Yes probably the plugin modifies maximum health of player and the inventory serializer saves that data too. I'll add option to modify what inventory serializer should save.
